import type { Asset, Offer, ReviewCase } from '../shared/types';
import metadata from './asset-metadata.json';

/** Authored fictional fixtures. No finding in this file was generated by a scanner. */
export const offers: Offer[] = [
  {
    id: 'offer-personal-loan-v3', product: 'personal_loan', name: 'Personal loan / Standard',
    version: 'PL-2026.09 / v3', validFrom: '2026-09-01', validTo: '2026-11-30',
    facts: [
      { label: 'Product', value: 'Unsecured, closed-end personal loan' },
      { label: 'Origination fee', value: 'Mandatory 5% of principal; deducted from proceeds' },
      { label: 'Internal proceeds example', value: '$10,000 principal - $500 fee = $9,500 proceeds' },
      { label: 'Eligibility', value: 'Credit approval required. Terms vary by applicant.' },
      { label: 'Campaign scope', value: 'Affiliate social creative and its named destination' },
    ],
    disclosure: 'No zero-fee variant exists in this fictional offer. Revised creative states that an origination fee applies and is deducted from proceeds. This reference supplies no advertised rate, APR, or payment amount.',
    source: 'Fictional ClearPath Product team. Supporting reference: personal-loan.pdf. Demo facts only.',
  },
  {
    id: 'offer-credit-card-v2', product: 'credit_card', name: 'Everyday credit card',
    version: 'CC-2026.09 / v2', validFrom: '2026-09-01', validTo: '2026-11-30',
    facts: [
      { label: 'Product', value: 'General-purpose consumer credit card' },
      { label: 'Annual fee', value: '$0 annual fee' },
      { label: 'Eligibility', value: 'Credit approval required; no guaranteed approval' },
      { label: 'Campaign scope', value: 'Static brand-awareness social image, without an application CTA' },
      { label: 'Claims not included', value: 'No APR, rewards, introductory-rate, or credit-limit claim' },
    ],
    disclosure: 'This reference covers the fictional brand-awareness concept. Any later application, pricing claim, rewards claim, or destination requires its own applicable terms and review.',
    source: 'Fictional ClearPath Product team. Supporting reference: credit-card.pdf. Demo facts only.',
  },
  {
    id: 'offer-mortgage-v1', product: 'mortgage', name: 'Mortgage prequalification',
    version: 'MTG-2026.09 / v1', validFrom: '2026-09-01', validTo: '2026-11-30',
    facts: [
      { label: 'Product', value: 'Mortgage prequalification estimate' },
      { label: 'Meaning', value: 'An estimate; not approval or a commitment to lend' },
      { label: 'Conditions', value: 'Credit approval, verification, and underwriting required' },
      { label: 'Campaign scope', value: 'Affiliate social image linked to a prequalification page' },
      { label: 'Claims not included', value: 'No rate, APR, down payment, or monthly payment advertised' },
    ],
    disclosure: 'Preserve the distinction between a preliminary estimate and a lending decision. The linked page must be supplied as a rendered destination before this campaign can be reviewed as a complete package.',
    source: 'Fictional ClearPath Product team. Supporting reference: mortgage.pdf. Demo facts only.',
  },
];

export interface DemoExample {
  key: string;
  case: ReviewCase;
  /** Source paths are relative to the repository root. Copy into private case storage. */
  assets: { assetId: string; path: string }[];
}

const facts = metadata as Record<string, Pick<Asset, 'name' | 'mime' | 'size' | 'sha256'>>;
const asset = (id: string, path: string, createdAt: string): Asset => ({
  ...facts[path], id, createdAt,
});
const reviewer = 'Maya Chen';
const loanAt = '2026-09-27T15:10:00.000Z';
const loanReviewAt = '2026-09-27T16:05:00.000Z';
const cardAt = '2026-09-27T14:25:00.000Z';
const mortgageAt = '2026-09-26T18:30:00.000Z';

const loan: ReviewCase = {
  id: 'example-personal-loan', reference: 'CP-1042', title: 'Make room for what’s next',
  product: 'personal_loan', submitter: 'Nina Patel', submitterEmail: 'nina@northstar.example',
  channel: 'Affiliate / paid social', launchDate: '2026-10-05', owner: reviewer, nextOwner: reviewer,
  waitingReason: '', status: 'in_review', version: 1, createdAt: loanAt, updatedAt: loanReviewAt,
  example: true, confirmedRevisionId: 'loan-r1',
  assets: [
    asset('loan-ad-v1', 'public/fixtures/loan/v1/social-ad.png', loanAt),
    asset('loan-offer', 'public/fixtures/offers/personal-loan.pdf', loanAt),
  ],
  revisions: [{
    id: 'loan-r1', number: 1, createdAt: loanAt, submittedBy: 'Nina Patel',
    summary: 'First submission: October partner social image. Landing page link included; rendition to follow.',
    offerId: offers[0].id, intendedUse: 'Northstar affiliate paid-social campaign. Review the exact image and the linked personal-loan destination together.',
    copy: 'Proposed post caption: Make room for what’s next with a ClearPath personal loan. Credit approval required. Sponsored by ClearPath.',
    destinationUrl: 'https://clearpath.example/personal-loans',
    components: [{ assetId: 'loan-ad-v1', role: 'creative' }, { assetId: 'loan-offer', role: 'evidence' }],
  }],
  findings: [
    {
      id: 'loan-f1', number: 1, kind: 'correction', title: 'Fee claim conflicts with the offer',
      detail: 'The image says “No origination fee.” The supplied PL-2026.09 / v3 reference requires a 5% fee for this offer. Its internal $10,000 example deducts $500 from proceeds.',
      request: 'Replace the zero-fee claim with “Origination fee applies” and explain that it is deducted from proceeds. Return the revised original image.',
      location: 'Social image / green fee callout and footer', assetId: 'loan-ad-v1', owner: 'Nina Patel',
      material: true, status: 'open', createdAt: loanReviewAt, createdBy: reviewer, revisionId: 'loan-r1',
    },
    {
      id: 'loan-f2', number: 2, kind: 'evidence', title: 'Destination rendition is missing',
      detail: 'The image invites consumers to explore loan options, but the package contains only a URL. The actual destination layout and terms have not been supplied.',
      request: 'Attach a complete rendered PDF of the proposed destination, including its terms section, and confirm it is the page linked by this creative.',
      location: 'Destination / clearpath.example/personal-loans', assetId: 'loan-ad-v1', owner: 'Nina Patel',
      material: true, status: 'open', createdAt: loanReviewAt, createdBy: reviewer, revisionId: 'loan-r1',
    },
  ],
  notes: [{ id: 'loan-n1', text: 'Sample review: I compared the original social image with the supplied offer reference. Two material findings remain open.', author: reviewer, createdAt: loanReviewAt }],
  decisions: [], drafts: [],
  history: [
    { id: 'loan-h1', type: 'submitted', text: 'Original image and offer reference received from Northstar. Destination URL supplied without a rendition.', actor: 'Nina Patel', createdAt: loanAt, revisionId: 'loan-r1' },
    { id: 'loan-h2', type: 'intake_confirmed', text: 'Confirmed image as creative and offer reference as supporting evidence. Missing destination recorded for follow-up.', actor: reviewer, createdAt: '2026-09-27T15:40:00.000Z', revisionId: 'loan-r1' },
    { id: 'loan-h3', type: 'finding_added', text: 'Two findings added: incorrect fee claim and missing destination rendition.', actor: reviewer, createdAt: loanReviewAt, revisionId: 'loan-r1' },
  ],
};

const card: ReviewCase = {
  id: 'example-credit-card', reference: 'CP-1041', title: 'Everyday, simply',
  product: 'credit_card', submitter: 'Alex Rivera', submitterEmail: 'alex@clearpath.example',
  channel: 'Owned / organic social', launchDate: '2026-10-02', owner: reviewer, nextOwner: reviewer,
  waitingReason: '', status: 'in_review', version: 1, createdAt: cardAt, updatedAt: '2026-09-27T15:15:00.000Z',
  example: true, confirmedRevisionId: 'card-r1',
  assets: [asset('card-ad', 'public/fixtures/card/social-ad.png', cardAt), asset('card-offer', 'public/fixtures/offers/credit-card.pdf', cardAt)],
  revisions: [{
    id: 'card-r1', number: 1, createdAt: cardAt, submittedBy: 'Alex Rivera',
    summary: 'Brand-awareness social image for the Everyday credit card. No application or linked destination in this scope.',
    offerId: offers[1].id, intendedUse: 'One static brand-awareness post on ClearPath’s own social account. No application CTA, pricing claim, rewards claim, or destination is included.',
    copy: 'Meet ClearPath Everyday. Simple by design. No annual fee. Credit approval required.', destinationUrl: '',
    components: [{ assetId: 'card-ad', role: 'creative' }, { assetId: 'card-offer', role: 'evidence' }],
  }],
  findings: [],
  notes: [{ id: 'card-n1', text: 'Sample review: the “No annual fee” statement agrees with CC-2026.09 / v2. Scope is the supplied brand-awareness image and caption only. Decision pending.', author: reviewer, createdAt: '2026-09-27T15:15:00.000Z' }],
  decisions: [], drafts: [],
  history: [
    { id: 'card-h1', type: 'submitted', text: 'Brand-awareness image and supporting offer reference submitted.', actor: 'Alex Rivera', createdAt: cardAt, revisionId: 'card-r1' },
    { id: 'card-h2', type: 'intake_confirmed', text: 'Confirmed the image, caption, offer version, and limited intended use.', actor: reviewer, createdAt: '2026-09-27T15:00:00.000Z', revisionId: 'card-r1' },
  ],
};

const mortgage: ReviewCase = {
  id: 'example-mortgage', reference: 'CP-1038', title: 'A clearer first step home',
  product: 'mortgage', submitter: 'Jordan Wells', submitterEmail: 'jordan@harborhome.example',
  channel: 'Affiliate / paid social', launchDate: '2026-10-07', owner: reviewer, nextOwner: 'Jordan Wells',
  waitingReason: 'Harbor Home needs to supply the rendered prequalification destination. A URL alone does not show the consumer experience.',
  status: 'waiting', version: 1, createdAt: mortgageAt, updatedAt: '2026-09-26T20:00:00.000Z', example: true, confirmedRevisionId: 'mortgage-r1',
  assets: [asset('mortgage-ad', 'public/fixtures/mortgage/social-ad.jpg', mortgageAt), asset('mortgage-offer', 'public/fixtures/offers/mortgage.pdf', mortgageAt)],
  revisions: [{
    id: 'mortgage-r1', number: 1, createdAt: mortgageAt, submittedBy: 'Jordan Wells',
    summary: 'Mortgage prequalification social image. Partner landing page is still being finalized.', offerId: offers[2].id,
    intendedUse: 'Harbor Home affiliate social creative leading to a ClearPath prequalification destination. The linked page is part of campaign review scope.',
    copy: 'A clearer first step closer to home. Explore mortgage prequalification with ClearPath. Sponsored by ClearPath. Prequalification is an estimate, not a commitment to lend.',
    destinationUrl: 'https://clearpath.example/mortgage',
    components: [{ assetId: 'mortgage-ad', role: 'creative' }, { assetId: 'mortgage-offer', role: 'evidence' }],
  }],
  findings: [{
    id: 'mortgage-f1', number: 1, kind: 'evidence', title: 'Prequalification destination needs review',
    detail: 'The original JPG is readable and states the prequalification limitation. The linked destination has not been supplied, so its actual presentation and continuation of the claim remain unreviewed.',
    request: 'Provide a rendered copy of the complete proposed destination, including eligibility language and the next-step CTA.',
    location: 'Destination / clearpath.example/mortgage', assetId: 'mortgage-ad', owner: 'Jordan Wells', material: true,
    status: 'open', createdAt: '2026-09-26T19:30:00.000Z', createdBy: reviewer, revisionId: 'mortgage-r1',
  }],
  notes: [{ id: 'mortgage-n1', text: 'Sample review: waiting on the affiliate’s destination rendition. The linked page must be reviewed before approval.', author: reviewer, createdAt: '2026-09-26T20:00:00.000Z' }],
  decisions: [], drafts: [],
  history: [
    { id: 'mortgage-h1', type: 'submitted', text: 'Original JPG and offer reference received.', actor: 'Jordan Wells', createdAt: mortgageAt, revisionId: 'mortgage-r1' },
    { id: 'mortgage-h2', type: 'intake_confirmed', text: 'Confirmed submitted assets and recorded missing destination.', actor: reviewer, createdAt: '2026-09-26T19:00:00.000Z', revisionId: 'mortgage-r1' },
    { id: 'mortgage-h3', type: 'waiting', text: 'Waiting for Jordan Wells to provide the prequalification destination rendition.', actor: reviewer, createdAt: '2026-09-26T20:00:00.000Z', revisionId: 'mortgage-r1' },
  ],
};

export const examples: DemoExample[] = [
  { key: 'personal-loan', case: loan, assets: [{ assetId: 'loan-ad-v1', path: 'public/fixtures/loan/v1/social-ad.png' }, { assetId: 'loan-offer', path: 'public/fixtures/offers/personal-loan.pdf' }] },
  { key: 'credit-card', case: card, assets: [{ assetId: 'card-ad', path: 'public/fixtures/card/social-ad.png' }, { assetId: 'card-offer', path: 'public/fixtures/offers/credit-card.pdf' }] },
  { key: 'mortgage', case: mortgage, assets: [{ assetId: 'mortgage-ad', path: 'public/fixtures/mortgage/social-ad.jpg' }, { assetId: 'mortgage-offer', path: 'public/fixtures/offers/mortgage.pdf' }] },
];
